export const loginTokens = {
  compactWidthThreshold: 375,
  wideWidthThreshold: 430,
  clockLogo: {
    tickCount: 12,
    tickStepDegrees: 30,
    majorTickEvery: 3,
    majorTickInnerRadius: 20,
    minorTickInnerRadius: 22,
    svgSize: 90,
    viewBoxSize: 64,
    center: 32,
    outerRadius: 26,
    outlineStrokeWidth: 2.5,
    majorTickStrokeWidth: 2,
    minorTickStrokeWidth: 1,
    minorTickOpacity: 0.35,
    handLongY: 10,
    handLongStrokeWidth: 2,
    handShortX: 19,
    handShortY: 22,
    handShortStrokeWidth: 2.5,
    accentHandFromY: 36,
    accentHandToX: 44,
    accentHandToY: 18,
    accentHandStrokeWidth: 1.5,
    centerDotRadius: 2.5,
  },
  titleLetterSpacing: 0.6,
  createAccountLetterSpacing: 0.2,
  formAreaMaxWidth: 420,
  formAreaCompactMaxWidth: 360,
  formAreaWideMaxWidth: 460,
  createAccountButtonMinHeight: 47,
  createAccountButtonPressedOpacity: 0.88,
  createAccountButtonPressedScale: 0.99,
  modalOverlayBackground: "rgba(0, 0, 0, 0.35)",
  modalContentMaxWidth: 340,
  modalContentBackground: "#FFFFFF",
  modalShadowOpacity: 0.08,
  modalPrimaryTextColor: "#FFFFFF",
} as const;
