export const colors = {
  background: "#FFFFFF",
  backgroundSecondary: "#FCF9F8",
  surface: "#FFFFFF",
  surfaceWarm: "#FDF9F8",
  surfacePink: "#FAF6F4",
  surfaceMint: "#F7F4F3",
  textPrimary: "#3E2C28",
  textSecondary: "#8C7B75",
  textMuted: "#A3938E",
  border: "#E6DAD6",
  borderSoft: "#F1EAE8",
  shadow: "#5A3E36",
  primary: "#5A3E36",
  primaryStrong: "#4A3228",
  accentCream: "#F6EEE8",
  accentPink: "#F4ECEA",
  accentPinkStrong: "#E8D7D1",
  accentMint: "#ECE6E3",
  danger: "#C35A5A",
  warning: "#B27A3F",
  success: "#3D9D5A",
  priorityRed: "#e51c23",
  priorityYellow: "#FFD700",
  priorityGreen: "#4CD964",
  urgentBg: "#F8F3F1",
  urgentPill: "#FFA94D",
  buttonBg: "#5A3E36",
  buttonText: "#FFFFFF",
  cardHighlight: "#F8F3F1",
  info: "#8C7B75",
  chipBg: "#FFFFFF",
  chipBgActive: "#F4ECEA",
  overlay: "rgba(90, 62, 54, 0.45)",
} as const;

export type ColorToken = keyof typeof colors;
