export const constants = {
  clockLogo: {
    tickCount: 12,
    tickStepDegrees: 30,
    majorTickEvery: 3,
    majorTickInnerRadius: 20,
    minorTickInnerRadius: 22,
    svgSize: 90,
    viewBoxSize: 64,
    center: 32,
    outerRadius: 26,
    outlineStrokeWidth: 2.5,
    majorTickStrokeWidth: 2,
    minorTickStrokeWidth: 1,
    minorTickOpacity: 0.35,
    handLongY: 10,
    handLongStrokeWidth: 2,
    handShortX: 19,
    handShortY: 22,
    handShortStrokeWidth: 2.5,
    accentHandFromY: 36,
    accentHandToX: 44,
    accentHandToY: 18,
    accentHandStrokeWidth: 1.5,
    centerDotRadius: 2.5,
  },
  home: {
    heroGlowPulseDurationMs: 2400,
    toastDurationMs: 1800,
    swipeableFriction: 1.4,
    swipeableRightThreshold: 30,
    emptyStateBlurIntensity: 45,
    searchBlurIntensity: 45,
    searchIconSize: 20,
    violetOrbBackground: "rgba(138, 43, 226, 0.15)",
  },
  card: {
    defaultGradient: ["#FFFFFF", "#F8FAFC"] as const,
    highlightedGradient: ["#F8FAFC", "#F1F5F9"] as const,
    innerBorder: "rgba(255, 255, 255, 0.4)",
  },
  animations: {
    quick: 150,
    normal: 300,
  },
  typography: {
    letterSpacing: {
      tight: 0.1,
      normal: 0.2,
      relaxed: 0.5,
    },
  },
} as const;
