export {
    ANDROID_DATE_PICKER_LOCALE,
    APP_VERSION,
    COMPLETED_LABEL_OPTIONS,
    DATE_DISPLAY_LOCALE,
    DATE_DISPLAY_OPTIONS,
    DATE_LOCALE_BY_LANGUAGE,
    DUE_LABEL_OPTIONS,
    HISTORY_COMPLETED_AT_OPTIONS,
    IOS_DATE_PICKER_LOCALE,
    LANGUAGE_PROVIDER_ERROR,
    TIME_DISPLAY_LOCALE,
    TIME_DISPLAY_OPTIONS
} from "./app-metadata";
export { getFirebaseConfigFromEnv } from "./env";

